K22CNT2-VuDucKhoa-project2/Models/EF/Categor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace K22CNT2_VuDucKhoa_project2.Models.EF
{
    [Table("tb_Categor")]
    public class Categor: CommonAbstract
    {
        public Categor() 
        {
            this.News = new HashSet<New>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage ="ten k dc de trong")]
        [StringLength(150)]
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Descriptio { get; set; }
        [StringLength(150)]

        public string SeoTitle { get; set; }
        [StringLength(250)]

        public string SeoDescriptio { get; set; }
        public int Position { get; set; }
        [StringLength(150)]

        public string SeoKeyWords { get; set; }
        public ICollection<New>News { get; set; }
        public ICollection<Post> Posts { get; set; }

    }
}

K22CNT2-VuDucKhoa-project2/Areas/Admin/Controllers/CategorController.cs
using K22CNT2_VuDucKhoa_project2.Models;
using K22CNT2_VuDucKhoa_project2.Models.EF;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace K22CNT2_VuDucKhoa_project2.Areas.Admin.Controllers
{
    public class CategorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Categor
        public ActionResult Index()
        {
            var items = db.Categors;
            return View(items);
        }
        public ActionResult Add() 
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Categor model) 
        {
            if (ModelState.IsValid)
            {
                model.CreateDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.Alias = K22CNT2_VuDucKhoa_project2.Models.Commons.Filter.FilterChar(model.Title);
                db.Categors.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var item = db.Categors.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categor model)
        {
            if (ModelState.IsValid)
            {
                db.Categors.Attach(model);
                model.ModifiedDate = DateTime.Now;
                model.Alias = K22CNT2_VuDucKhoa_project2.Models.Commons.Filter.FilterChar(model.Title);
                db.Entry(model).Property(x=>x.Title).IsModified=true;
                db.Entry(model).Property(x=>x.Descriptio).IsModified=true;
                db.Entry(model).Property(x=>x.Alias).IsModified=true;
                db.Entry(model).Property(x=>x.SeoDescriptio).IsModified=true;
                db.Entry(model).Property(x=>x.SeoKeyWords).IsModified=true;
                db.Entry(model).Property(x=>x.SeoTitle).IsModified=true;
                db.Entry(model).Property(x=>x.Position).IsModified=true;
                db.Entry(model).Property(x=>x.ModifiedDate).IsModified=true;
                db.Entry(model).Property(x=>x.ModifierBy).IsModified=true;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.Categors.Find(id);
            if (item == null)
            {
                //var DeleteItem=db.Set<Categor>.Attach(item);//
                db.Categors.Remove(item);
                db.SaveChanges();
                return Json(new { success=true });
            }
            return Json(new { success = false });

        }
    }
}

K22CNT2-VuDucKhoa-project2/Areas/Admin/Views/Categor/Add.cshtml
@model K22CNT2_VuDucKhoa_project2.Models.EF.Categor
@{
    ViewBag.Title = "Them moi danh muc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section navaiheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/Home" class="nav-link">Trang chu</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/categor" class="nav-link">danh muc</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">them moi</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Them moi danh muc</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh muc</a></li>
                    <li class="breadcrumb-item active">Them moi</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">thong tin them moi</h3>


        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Add", "Categor", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Ten</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "ten danh muc" })
                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Mo Ta</label>
                        @Html.TextAreaFor(x => x.Descriptio, new { @Class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">thu tu</label>
                        @Html.TextBoxFor(x => x.Position, new { @class = "form-control", @Value="1" })
                    
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoTitle</label>
                        @Html.TextAreaFor(x => x.SeoTitle, new { @Class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoDescriptio</label>
                        @Html.TextAreaFor(x => x.SeoDescriptio, new { @Class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoKeyWords</label>
                        @Html.TextAreaFor(x => x.SeoKeyWords, new { @Class = "form-control" })
                    </div>
                    <div class="form-group">
                        <a href="/admin/categor" class="btn btn-danger">quay lai</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
                    
                }

            </div>
        </div>
    </div>

    </div>
    <!-- /.card-body -->
    <div class="card-footer">

    </div>
    <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

K22CNT2-VuDucKhoa-project2/Areas/Admin/Views/Categor/Edit.cshtml
@model K22CNT2_VuDucKhoa_project2.Models.EF.Categor
@{
    ViewBag.Title = "Cap Nhat danh muc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section navaiheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/Home" class="nav-link">Trang chu</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/categor" class="nav-link">danh muc</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">cap Nhat</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Them moi danh muc</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh muc</a></li>
                    <li class="breadcrumb-item active">Cap Nhat</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">thong tin cap nhat</h3>


        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Edit", "Categor", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x=>x.Id)
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Ten</label>
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "ten danh muc" })
                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Mo Ta</label>
                            @Html.TextAreaFor(x => x.Descriptio, new { @Class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">thu tu</label>
                            @Html.TextBoxFor(x => x.Position, new { @class = "form-control", @Value = "1" })

                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">SeoTitle</label>
                            @Html.TextAreaFor(x => x.SeoTitle, new { @Class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">SeoDescriptio</label>
                            @Html.TextAreaFor(x => x.SeoDescriptio, new { @Class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">SeoKeyWords</label>
                            @Html.TextAreaFor(x => x.SeoKeyWords, new { @Class = "form-control" })
                        </div>
                        <div class="form-group">
                            <a href="/admin/categor" class="btn btn-danger">quay lai</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>

                    </div>

                }

            </div>
        </div>
    </div>

    </div>
    <!-- /.card-body -->
    <div class="card-footer">

    </div>
    <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

K22CNT2-VuDucKhoa-project2/Areas/Admin/Views/Categor/Index.cshtml
@model IEnumerable<K22CNT2_VuDucKhoa_project2.Models.EF.Categor>
@{
    ViewBag.Title = "Danh Muc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section navaiheader
    {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/home" class="nav-link">Trang chu</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/categor" class="nav-link">danh muc</a>
        </li>
    </ul>

}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quan ly Danh Muc</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chu</a></li>
                    <li class="breadcrumb-item active">Danh Muc</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sach danh muc</h3>

            <div class="card-tools">
                <a href="/admin/categor/add" class="btn btn-primary">them moi</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>ten danh muc</th>
                        <th>thu tu</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {

                            <tr id="trow_@item.Id">
                                <td>@i</td>
                                <td>@item.Title</td>
                                <td>@item.Position</td>
                                <td>
                                    <a href="/admin/categor/edit/@item.Id" class="btn btn-sm btn-primary">sua</a>
                                    <a href="/admin/categor/edit/" data-id="@item.Id" class="btn btn-sm btn-danger btnDelete">xoa</a>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {

                        <tr>
                            <td colspan="4">khong co ban ghi nao</td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('ban co muon xoa ban ghi nay khong');
                if (conf === true) {
                    $.ajax({
                        url:'/admin/categor/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
}